version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://pkd:pkd_password@db:5432/pkd_compass?schema=public
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: pkd
      POSTGRES_PASSWORD: pkd_password
      POSTGRES_DB: pkd_compass
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
